### ISSUE TITLE
JSLint complains about JSLint directive

### ISSUE THREAD

**Issue by arctwelve** [georapbox/brackets-JSLint-Configurator#8]
Maybe I'm doing something wrong, but when I use the extension to insert a directive into a .js file the directive is recognized as a JSLint problem.

Release 1.5 build 1.5.0-16538 (release cf9cf4698) 
Windows 10

![error](https://cloud.githubusercontent.com/assets/4304536/10865166/635c9af6-7fd9-11e5-8d6a-97054b5d734a.png)

**Comment by georapbox** [comment]
It seems that "ass" is no longer used as a directive. That's why JSLint extension complains. So I totally removed it as an option from the configurator.
